[Feat]: add RSK
block-wallet/extension pull request #230
Opened 2022-11-22 18:56 UTC by leablock

# Name of the feature/issue

Add RSK Mainnet and Testnet

## Description
- Add as default networks
  - Use nodes that support "eth_getLogs" https://developers.rsk.co/rif/identity/mvp/run/#1-run-the-infrastructure
  - Add the nodes in chains-assets https://github.com/block-wallet/chains-assets/pull/74 so that they're verified
- Add migration
- Add both in chain-fee https://github.com/block-wallet/chain-fee-data-service/pull/52
- Disable "showGasLevels" because "slow" level may be enough in some cases and the transaction could be rejected

![image](https://user-images.githubusercontent.com/98833290/203397888-8fd81b29-fa70-4376-9638-3e3f43a7dcbe.png)
![image](https://user-images.githubusercontent.com/98833290/203397947-82028f03-86c0-4546-8fc3-3865dd0af2dc.png)
![image](https://user-images.githubusercontent.com/98833290/203398009-7deb3092-6c80-4032-a8b6-b276fcafd05b.png)

2022-11-22 19:24 UTC, fpezzola requested changes
Please read my comment

2022-11-22 19:24 UTC, fpezzola commented on packages/background/src/infrastructure/stores/migrator/migrations/migration-52.ts
> +        const updatedNetworks = { ...availableNetworks };
We have to take into account that the user may already have added this network to his wallet. So, we should first look for the RSK chain ID in the user's network list and if it exists:
- Delete the user's RSK network record, indexed as `CHAIN-30`
- Update some of our parameters with the user's configured network (like the RPC url, name, order, so on...)

2022-11-22 19:24 UTC, fpezzola commented on packages/background/src/infrastructure/stores/migrator/migrations/migration-52.ts
> +        const updatedNetworks = { ...availableNetworks };
You can use the `getNonNativeNetworkKey` helper to get the Key

2022-11-24 13:48 UTC, fpezzola commented on packages/background/src/infrastructure/stores/migrator/migrations/migration-53.ts
> +        const rsk = {
Why do you duplicate this? Can't you use `INITIAL_NETWORKS.RSK`?

2022-11-24 13:56 UTC, fpezzola commented on packages/background/src/infrastructure/stores/migrator/migrations/migration-53.ts
> +        updatedNetworks = addNetworkWithPreviousUserValues(
I'd limit the scope of the helper to only merge two configurations. 

```
//migration53
const userCurrentNetworkConfig = persistedState.NetworkController.find(network => network.chainId === INITIAL_NETWORKS.RSK.chainId || {};

updatedNetworks['RSK']= newNativelySupportedNetwork(INITIAL_NETWORKS.RSK, userCurrentNetworkConfig);


//networks.test
const newNativelySupportedNetwork(baseNetworkConfig: Network, userCurrentNetworkConfig: Network) : Network => {
  return { 
     ....baseNetworkConfig,
    order: userCurrentNetworkConfig.order ?? baseNetworkConfig.order,
    desc: userCurrentNetworkConfig?.desc || baseNetworkConfig.desc,
    rpcUrl: userCurrentNetworkConfig.rpcUrl || baseNetworkConfig.rpcUrl,
    blockExplorerUrl: userCurrentNetworkConfig.blockExplorerUrl || baseNetworkConfig.blockExplorerUrl,
    nativelySupported: true
   }
}
```

2022-11-24 13:57 UTC, fpezzola commented on packages/background/src/infrastructure/stores/migrator/migrations/migration-53.ts
> +            order: updatedNetworks.LOCALHOST.order++,
`order: updatedNetworks.LOCALHOST.order + 1,`

2022-11-24 18:02 UTC, fpezzola approved these changes
lgtm! great work 👏

2022-11-25 15:32 UTC, julianariel approved these changes

2022-11-25 17:04 UTC, merged